[workspace]

members = [
    "bin/node/node",
    "bin/node/runtime",
    "modules/substrate",
    "modules/ethereum",
    "modules/ethereum-contract/builtin",
    "modules/currency-exchange",
    "modules/header-chain",
    "relays/ethereum",
]
