name:                              Publish images to Docker hub

on:
  pull_request:
  push:
    branches:
      - master
      - 3x8_use_buildah
    tags:
      - v*
    paths-ignore:
      - '**/README.md'
      - diagrams/*
      - docs/*
  schedule:                        # Nightly build
    - cron:                        '0 1 * * *'

jobs:
                                   ## Publish to Docker hub
  publish:
    name:                          Publishing
    strategy:
      matrix:
        project:
          - rialto-bridge-node
          - millau-bridge-node
          - ethereum-poa-relay
          - substrate-relay
        include:
          - project: rialto-bridge-node
            healthcheck: http://localhost:9933/health
          - project: millau-bridge-node
            healthcheck: http://localhost:9933/health
          - project: ethereum-poa-relay
            healthcheck: http://localhost:9616/metrics
          - project: substrate-relay
            healthcheck: http://localhost:9616/metrics

    runs-on:                       self-hosted
    container:
      image:                       docker:git
    steps:

      - name:                      Cancel Previous Runs
        uses:                      styfle/cancel-workflow-action@0.4.1
        with:
          access_token:            ${{ github.token }}

      - name:                      Checkout sources & submodules
        uses:                      actions/checkout@master
        with:
          fetch-depth:             5
          submodules:              recursive

      - name: Prepare
        id: prep
        run: |
          DOCKER_IMAGE=paritytech/bridge-dependencies
          VERSION=latest
          if [[ $GITHUB_REF == refs/tags/* ]]; then
            VERSION=${GITHUB_REF#refs/tags/}
          elif [[ $GITHUB_REF == refs/heads/* ]]; then
            VERSION=$(echo ${GITHUB_REF#refs/heads/} | sed -r 's#/+#-#g')
          fi
          TAGS=${DOCKER_IMAGE}:${VERSION}
          TAGS=$TAGS,${DOCKER_IMAGE}:sha-${GITHUB_SHA::8}
          echo ::set-output name=TAGS::${TAGS}
          echo ::set-output name=DATE::$(date +%d-%m-%Y)

      - name:                      Set up Docker Buildx
        uses:                      docker/setup-buildx-action@v1

      - name:                      Login to DockerHub
        uses:                      docker/login-action@v1
        with:
          username:                ${{ secrets.DOCKER_USER }}
          password:                ${{ secrets.DOCKER_PASSWORD }}

      - name:                      Build and push
        uses:                      docker/build-push-action@v2
        with:
          context:                 .
          file:                    ./Dockerfile
          push:                    true
          cache-from:              type=registry,ref=paritytech/bridge-dependencies:latest
          cache-to:                type=inline
          tags:                    ${{ steps.prep.outputs.TAGS }}
          build-args: |
            PROJECT=${{ matrix.project }}
            HEALTH=${{ matrix.healthcheck }}
          labels: |
            org.opencontainers.image.title=${{ matrix.project }}
            org.opencontainers.image.description=${{ matrix.project }} - component of Parity Bridges Common
            org.opencontainers.image.source=${{ github.event.repository.html_url }}
            org.opencontainers.image.url=${{ github.event.repository.html_url }}
            org.opencontainers.image.documentation=${{ github.event.repository.html_url }}/README.md
            org.opencontainers.image.created=${{ steps.prep.outputs.DATE }}
            org.opencontainers.image.version=${{ steps.prep.outputs.TAG }}
            org.opencontainers.image.revision=${{ github.sha }}
            org.opencontainers.image.authors=devops-team@parity.io
            org.opencontainers.image.vendor=Parity Technologies
            org.opencontainers.image.licenses=GPL-3.0 License